version: "3"
services:
  worker_base:
    build: .
    env_file:
      - env_file
    environment:
      - POSTGRES_HOST=db
      - RABBIT_MQ_HOST=rabbit_mq
    command: 'false'

  app_worker:
    restart: always
    extends:
      service: worker_base
    command: gunicorn --config gunicorn.conf.py wsgi:app
    ports:
    - "5000:5000"
    depends_on:
      - db
      - rabbit_mq
      - migrations

  bg_worker:
    restart: on-failure
    extends:
      service: worker_base
    command: python background.py
    depends_on:
      - db
      - rabbit_mq
      - migrations

  rabbit_mq:
    image: library/rabbitmq:3.6-management
    ports:
    - "5672:5672"
    - "15672:15672"
    env_file:
      - env_file

  db:
    image: postgres:10
    restart: on-failure
    env_file:
      - env_file

  migrations:
    extends:
      service: worker_base
    command: flask db upgrade
    restart: on-failure
    depends_on:
      - db
      - rabbit_mq
